"""add content architecture (school levels, subjects, terms, units, weeks, lessons, resources, tags)

Revision ID: e527352baed9
Revises: 50404e32b951
Create Date: 2026-09-17 15:16:27.292030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e527352baed9'
down_revision: Union[str, None] = '50404e32b951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_fr', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('school_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_fr', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_fr')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_level_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_fr', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_level_id'], ['school_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subjects_school_level_id'), 'subjects', ['school_level_id'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_fr', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'code', name='uq_terms_subject_code')
    )
    op.create_index(op.f('ix_terms_subject_id'), 'terms', ['subject_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('brouillon', 'a_verifier', 'publie', 'archive', name='validation_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_term_id'), 'units', ['term_id'], unique=False)
    op.create_table('weeks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weeks_term_id'), 'weeks', ['term_id'], unique=False)
    op.create_index(op.f('ix_weeks_unit_id'), 'weeks', ['unit_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('title_ar', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('brouillon', 'a_verifier', 'publie', 'archive', name='validation_status'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'ELEVES', 'ENSEIGNANTS', 'ADMIN', name='visibility'), nullable=False),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('competencies', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_unit_id'), 'lessons', ['unit_id'], unique=False)
    op.create_index(op.f('ix_lessons_week_id'), 'lessons', ['week_id'], unique=False)
    op.create_table('lesson_tags',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'tag_id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type_id', sa.Uuid(), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_ar', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('brouillon', 'a_verifier', 'publie', 'archive', name='validation_status'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'ELEVES', 'ENSEIGNANTS', 'ADMIN', name='visibility'), nullable=False),
    sa.Column('language', sa.Enum('fr', 'ar', name='resource_language'), nullable=True),
    sa.Column('file_ref', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_ref', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_lesson_id'), 'resources', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_type_id'), 'resources', ['resource_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_resource_type_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_lesson_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('lesson_tags')
    op.drop_index(op.f('ix_lessons_week_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_unit_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_weeks_unit_id'), table_name='weeks')
    op.drop_index(op.f('ix_weeks_term_id'), table_name='weeks')
    op.drop_table('weeks')
    op.drop_index(op.f('ix_units_term_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_terms_subject_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_subjects_school_level_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('tags')
    op.drop_table('school_levels')
    op.drop_table('resource_types')
    # ### end Alembic commands ###
